### ISSUE TITLE
Roadmap 21.01.2018

### ISSUE THREAD

**Issue by Pzixel** [nebgnahz/cv-rs#40]
- [x] Create user script to enable easy OCV+CUDA configuration (#38)
- [x] Add `.gitattributes` (#38)
- [x] Enable rustfmt to allow better review and single source of truth in questions of how code should be written. (#39)
- [x] Get rid of libc, because of multiple compatibility issues. (#41)
- [x] Create user script to enable easy OCV+MinGW configuration (#42)
- [x] Get rid of `errors_chain` crate and use `failure` one ([see explanation](https://www.reddit.com/r/rust/comments/7h8v1z/errorchain_and_failure/)) (#44)
- [x] Fix cargo doc issues (#45)
- [x] Add more features such as cv::compareHist. (#47)
- [x] Get rid of macros such as `CVec`, `CResult` and so on and try to use templates. I have some ideas here. (#48)
- [x] Format C++ code. (#53)

**Comment by Pzixel** [comment]
Another idea is move examples to a separated project because otherwise you have dependencies (such as `getopts`) that library actually doesn't use.

**Comment by nebgnahz** [comment]
We can factor examples out and have each example become a standalone Cargo project.

**Comment by Pzixel** [comment]
Yep, that's what I mean

**Comment by Pzixel** [comment]
Wow, it's been 3 days and we already did almost all from the list.

**Comment by Pzixel** [comment]
@nebgnahz any progress in finding `cppfmt` for C code (last bullet of the list)? I recall that you was expecting code that is formatted in single manner.
